mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:mapper/*.xml
  type-aliases-package: com.springcloud.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
spring:
  datasource:
    dbcp2:
      initial-size: 5
      max-total: 10
      max-wait-millis: 2000
      min-idle: 5
    driver-class-name: org.gjt.mm.mysql.Driver
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/shopping
    username: root
